---
output:
  pdf_document:
    keep_tex: yes
    number_sections: yes
    citation_package: natbib  # comentado usa: pandoc-citeproc
    template: latex/templateMemoriaTFE.tex
    pandoc_args: ["--metadata-file=cabecera_capitulos.yaml"]
  html_document: default
#bibliography: bib/library.bib # descomentar si: editor visual RStudio  
---

<!-- escribir 2 para capítulo 3 -->
<!-- \setcounter{chapter}{2} --> 
<!-- \pagenumbering{arabic} -->

`r xfun::file_string('cabecera_capitulos.tex')`

```{r include=FALSE}
source("cabecera_chunk_inicio.R")
```


# Concepto de solución

En la teoría de juegos, un **concepto de solución** es una regla formal para predecir cómo se jugará un juego. Estas predicciones se denominan "soluciones", y describen las estrategias que adoptarán los jugadores y, por tanto, el resultado que puede esperarse del juego. 

En general, los conceptos de solución tratan de identificar perfiles de estrategias que puedan considerarse racionales o estables, teniendo en cuenta que cada jugador toma sus decisiones considerando las posibles acciones de los demás participantes.

Los conceptos de solución más comúnmente utilizados son conceptos de equilibrio, el más famoso de ellos es el equilibrio de Nash.

En muchos juegos, un mismo concepto de solución puede dar lugar a varias soluciones posibles. Por este motivo, la teoría de juegos introduce en ocasiones refinamientos de equilibrio, cuyo objetivo es reducir el conjunto de soluciones y seleccionar aquellas que resultan más razonables.

A continuación, se presentan algunos conceptos de solución:

## Estrategias dominadas y dominantes

Una estrategia de un jugador se dice dominante si es tan buena o más que cualquier otra como respuesta a cualquier combinación de estrategias que elijan los demás jugadores, y una estrategia dada $s_i$ de un jugador se dice que está dominada por otra estrategia $s'_i$ del mismo jugador si la segunda le conviene más que la primera, independientemente de lo que hagan los otros jugadores. El argumento básico de dominación consiste en que un jugador racional no debería jugar estrategias dominadas y en que, en caso de saber que otros jugadores son racionales, debería suponer que éstos no van a jugar tal clase de estrategias.

**Definición 3.1.** En el juego $G = \{S_1, \ldots, S_n; u_1,\ldots,u_n\}$, sean $s'_i$ y $s''_i$ dos estrategias del jugador *i*.

  a)  Decimos que $s'_i$ está **dominada**, o también **débilmente dominada**, por $s''_i$ cuando la desigualdad
  $$u_i(s_1,\ldots,s_{i-1},s'_i,s_{i+1},\ldots,s_n)\le u_i(s_1,\ldots,s_{i-1},s''_i,s_{i+1},\ldots,s_n)$$
  
  se cumple para toda combinación de estrategias $s_{-i}$ de los otros jugadores, y para alguna de esas combinaciones se cumple de modo estricto. Decimos de manera equivalente que $s''_i$ **domina** a $s'_i$. (Es decir, siempre le conviene usar $s''_i$ al menos tanto como usar $s'_i$, hagan lo que hagan los otros jugadores, y a veces le conviene más)
  
  b) Decimos que $s'_i$ está **estrictamente dominada** por $s''_i$ cuando la desigualdad
  $$u_i(s_1,\ldots,s_{i-1},s'_i,s_{i+1},\ldots,s_n)<u_i(s_1,\ldots,s_{i-1},s''_i,s_{i+1},\ldots,s_n)$$
  se cumple para toda combinación de estrategias $s_{-i}$ de los otros jugadores. (Es decir, le conviene más usar $s''_i$ que $s'_i$, hagan lo que hagan los otros jugadores)
  
  c)  Decimos que $s'_i$ es **no dominada** si no existe ninguna otra estrategia del jugador *i* que la domine, y decimos que $s'_i$ es **no dominada estrictamente** si no existe ninguna otra estrategia del jugador i que la domine estrictamente.
  

  
Por otra parte, el concepto de estrategia dominante que se define a continuación, se aplica a una estrategia de un jugador cuando ésta es tan buena o más que cualquier otra como respuesta a cualquier combinación de estrategias qie elijan los demás jugadores.

**Definición 3.2.** En el juegos $G = \{S_1,\ldots,S_n;u_1,\ldots,u_n\}$, sea $s'_i$ una estrategia del jugador *i*.

  a) Decimos qie $s'_i$ es **dominante** cuando la desigualdad
  $$u_i(s_1,\ldots,s_{i-1},s_i,s_{i+1},\ldots,s_n)\le u_i(s_1,\ldots,s_{i-1},s'_i,s_{i+1},\ldots,s_n)$$
  se cumple para toda estrategia $s_i$ de dicho jugador y para toda combinación de estrategias $s_{-i}$ de los otros jugadores. (Es decir, siempre le conviene usar la estrategia $s'_i$ al menos tanto como cualquier otra, hagan lo que hagan los otros jugadores)
    
  b)  Si todas las desigualdades se cumplen de manera estricta (para $s_i \neq s'_i$), decimos que $s'_i$ es **estrictamente dominante**.
  
\begin{tcolorbox}[colback=blue!10]
\textbf{Ejemplo 3.1} \\

Consideremos el siguiente juego de dos jugadores (Dilema del Prisionero)

\begin{table}[H]
\centering
\begin{tabular}{c|cc}
 & \multicolumn{2}{c}{\textbf{Preso 2}} \\ 
\textbf{Preso 1} & Callar & Confesar \\ \hline
Callar & (4,4) & (0,5) \\
Confesar & (5,0) & (1,1)
\end{tabular}
\caption{Pagos del Dilema del Prisionero}
\label{tab:dilema_prisionero}
\end{table}

\textbf{Análisis:}  

Para el jugador 1:

\[
u_1(\text{Callar, Callar}) = 4 < 5 = u_1(\text{Confesar, Callar})
\]

\[
u_1(\text{Callar, Confesar}) = 0 < 1 = u_1(\text{Confesar, Confesar})
\]

De manera análoga, para el jugador 2:

\[
u_2(\text{Callar, Callar}) = 4 < 5 = u_2(\text{Callar, Confesar})
\]

\[
u_2(\text{Confesar, Callar}) = 0 < 1 = u_2(\text{Confesar, Confesar})
\]

\textbf{Conclusión:}  

Para ambos jugadores, la estrategia \textbf{Callar} está \textbf{estrictamente dominada} por la estrategia \textbf{Confesar}.  
Por lo tanto, si los jugadores son racionales, ambos elegirán \textbf{Confesar} y el equilibrio estrictamente dominante es \((\text{Confesar}, \text{Confesar})\).
\end{tcolorbox}

### Uso de Estrategias Dominantes (UED)
Según este concepto de solución, pertenecen a la solución del juego todos aquellos perfiles de estrategias en los cuales cada jugador usa una estrategia dominante.

Naturalmente, en caso de ser aplicable, este concepto de solución es obvio, pues cualquier jugador racional jugará una estrategia dominante si dispone de ella, independientemente de cualquier otra consideración (y si tiene varias, jugará una de ellas). En particular lo hará independientemente de lo que sepa o suponga acerca de cómo van a jugar los otros jugadores, y de qué sepa acerca de las características de dichos jugadores. De hecho, incluso cabe la posibilidad de que los jugadores tengan un conocimiento muy limitado de aquellos aspectos del juego que afectan a los demás jugadores (por ejemplo, podrían no conocer los pagos de los otros), y aun así tender a jugar su estrategia dominante.

Por desgracia, este concepto de solución no siempre es aplicable. Los juegos en los que cada jugador tiene alguna estrategia dominante son más bien la excepción que la regla.

\begin{tcolorbox}[colback=blue!10]
\textbf{Ejemplo 3.2} \\

En el dilema del prisionero, este concepto sí es aplicable, pues en este caso cada jugador tiene una estrategia estrictamente dominante, que es confesar.

Mientras en el siguiente ejemplo  

\begin{table}[H]
\centering
\begin{tabular}{c|ccc}
 & \multicolumn{3}{c}{\textbf{Jugador 2}} \\ 
\textbf{Jugador 1} & I & C & D \\ \hline
A & (3,y) & (4,2) & (1,x) \\
M & (2,4) & (3,5) & (4,0) \\
B & (1,0) & (2,1) & (0,3)
\end{tabular}
\caption{Juego con estrategias estrictamente dominadas pero sin estrategias dominantes}
\label{tab:contraejemplo_UED}
\end{table}

\textbf{Conclusión:}  
En este juego, con x = y = 1, la estrategia B del jugador 1 (J1) está estrictamente dominada por las estrategias A y M. Pero ni A ni M son estrategias dominantes. Por otra parte, para el jugador 2 (J2) la estrategia I está estrictamente dominada por la estrategia C, pero ni C ni D son dominantes. Así pues, aunque el concepto de solución anterior no es aplicable, el argumento básico de dominación (ningún jugador racional debería jugar estrategias dominadas) nos permite concluir inmediatamente que ni J1 jugará B ni J2 jugará I, pero sólo nos permite esa conclusión
\end{tcolorbox}


### Eliminación Iterativa Estricta (EIE)

**Definición 3.3.** Dado un juego finito o infinito $G = \{S_1, \ldots, S_n; u_1, \ldots, u_n\}$, llamamos **Eliminación Iterativa Estricta (EIE)**, o bien **Eliminación Iterativa de Estrategias Estrictamente Dominadas**, al siguiente proceso de eliminación:

  **1º Paso.** De cada uno de los jugadores, y a la vez, se eliminan todas las estrategias que estén estrictamente dominadas en el juego inicial G. Se construye el juego reducido $G_1$ que resulta de tal eliminación.
  
  **2º Paso.** De cada uno de los jugadores, y a la vez, se eliminan todas las estrategias que estén estrictamente dominadas en el juego reducido $G_1$. Se construye el juego reducido $G_2$ que resulta de tal eliminación.
  
  Y así sucesivamente. Se acaba el proceso cuando ya no quedan, para ningún jugador, estrategias que eliminar. Denotamos $S^S_i$ al conjunto de las estrategias supervivientes del jugador i, y las llamamos estrategias iterativamente no dominadas.
  
De acuerdo con este concepto de solución, son soluciones todos los perfiles estratégicos constituidos por estrategias que sobreviven al proceso de eliminación iterativa estricta. LLamaremos $\mathbf{S^{EIE}}$ al conjunto de dichos perfiles estratégicos solución.

\begin{tcolorbox}[colback=blue!10]
\textbf{Ejemplo 3.3} \\

Dado el juego

\begin{table}[H]
\centering
\begin{tabular}{c|cc}
 & \multicolumn{2}{c}{\textbf{Jugador 2}} \\ 
\textbf{Jugador 1} & Izquierda & Derecha\\ \hline
Alta & (4,2) & (0,1) \\
Media & (1,2) & (2,4) \\
Baja & (3,3) & (4,2)
\end{tabular}
\caption{Juego G (EIE)}
\label{tab:EIE}
\end{table}

Puesto que la racionalidad de ambos jugadores es una información de dominio público, ambos jugadores son racionales y cada uno sabe que el otro lo es y además sabe que el otro lo sabe. En consecuencia, puede razonarse así:

El jugador 1 (J1), que es racional, elimina la estrategia \textbf{Media} porque está estrictamente dominada por \textbf{Baja} (pagos 1 frente a 3 y 2 frente a 4). El jugador 2 (J2) sabe que J1 es racional y por tanto sabe que J1 ha eliminado \textbf{Media}. Al comparar \textbf{Izquierda} con \textbf{Derecha} en ausencia de Media de J1, el jugador J2, que también es racional, deduce que \textbf{Izquierda} domina estrictamente a \textbf{Derecha} (pagos 2 frente a 1 y 3 frente a 2), por lo que elimina \textbf{Derecha}.

\begin{table}[H]
\centering
\begin{tabular}{c|c}
 & \multicolumn{1}{c}{\textbf{Jugador 2}} \\ 
\textbf{Jugador 1} & Izquierda\\ \hline
Alta & (4,2)\\
Baja & (3,3)
\end{tabular}
\caption{Juego $G_1$ (EIE)}
\label{tab:EIE}
\end{table}

El jugador J1 sabe que J2 es racional y que además J2 sabe que J1 es racional, y por tanto sabe que J2 ha eliminado \textbf{Derecha} como consecuencia de la eliminación por J1 de \textbf{Media}. Al comparar \textbf{Alta} con \textbf{Baja} en ausencia de \textbf{Derecha}, J1 deduce que \textbf{Alta} domina estrictamente a \textbf{Baja} (pago 4 frente a 3) por lo que elimina \textbf{Baja}.

\begin{table}[H]
\centering
\begin{tabular}{c|c}
 & \multicolumn{1}{c}{\textbf{Jugador 2}} \\ 
\textbf{Jugador 1} & Izquierda\\ \hline
Alta & (4,2)\\
\end{tabular}
\caption{Juego $G_2$ perfil superviviente único (EIE)}
\label{tab:EIE}
\end{table}

En conclusión, las únicas estrategias supervivientes al proceso EIE son \textbf{Alta} de J1 e \textbf{Izquierda} de J2. Ambas constituyen el único perfil solución del juego, es decir, $\mathbf{S^{EIE}}$ = \{(Alta, Izquierda)\}
\end{tcolorbox}


### Eliminación Iterativa Débil (EID)
**Definición 3.4.** Dado un juego finito o infinito $G = \{S_1,\ldots,S_n;u_1,\ldots,u_n\}$, llamamos **Eliminación Iterativa Débil (EID)**, o bien **Eliminación Iterativa de Estrategias Débilmente Dominadas**, al proceso de eliminación siguiente:

**1º Paso.** De cada uno de los jugadores, y a la vez, se elimina todas las estrategias que estén débilmente dominadas en el juego inicial G. Se construye el juego reducido $G_1$ que resulta de tal eliminación.

**2º Paso.** De cada uno de los jugadores, y a la vez, se eliminan todas las estrategias que estén débilmente dominadas en el juego reducido $G_1$. Se construye el juego reducido $G_2$ que resulta de tal eliminación.

Y así sucesivamente. Se acaba el proceso cuando ya no quedan, para ningún jugador i, estrategias que eliminar. Denotamos $S^S_i$ al conjunto de las estrategias supervivientes del jugador i, y las llamamos estrategias iterativamente no dominadas.

Desgraciadamente, y al contrario de lo que ocurre para los algoritmos de eliminación estricta, ahora el resultado final del proceso de eliminación sí depende del algoritmo utilizado, es decir, del orden y modo en que se han ido seleccionando las estrategias a eliminar.

Este concepto de solución determina como solución $\mathbf{S^{EID}}$.

\begin{tcolorbox}[colback=blue!10]
\textbf{Ejemplo 3.4} \\

Dado el juego

\begin{table}[H]
\centering
\begin{tabular}{c|ccc}
 & \multicolumn{3}{c}{\textbf{Jugador 2}} \\ 
\textbf{Jugador 1} & I & C & D\\ \hline
A & (3,1) & (4,2) & (1,2)\\
M & (2,4) & (3,5) & (4,0) \\
B & (1,0) & (2,1) & (0,3)
\end{tabular}
\caption{Juego G (EID)}
\label{tab:EID}
\end{table}

Puesto que la racionalidad de ambos jugadores es información de dominio público, ambos jugadores son racionales y cada uno sabe que el otro lo es y además sabe que el otro lo sabe. En consecuencia, puede razonarse del siguiente modo:

El jugador 1 (J1), que es racional, compara sus estrategias \textbf{A}, \textbf{M} y \textbf{B}. Al comparar \textbf{A} con \textbf{B}, observa que \textbf{A} proporciona siempre un pago mayor que \textbf{B} independientemente de la estrategia elegida por el jugador 2 (pagos 3 frente a 1 si J2 juega \textbf{I}, 4 frente a 2 si J2 juega \textbf{C}, y 1 frente a 0 si J2 juega \textbf{D}). Por tanto, la estrategia \textbf{B} está estrictamente dominada por \textbf{A} y J1 elimina \textbf{B}.

El jugador 2 (J2) sabe que J1 es racional y por tanto sabe que J1 ha eliminado la estrategia \textbf{B}. En consecuencia, J2 compara ahora sus estrategias considerando únicamente las estrategias \textbf{A} y \textbf{M} de J1. Al comparar \textbf{I} con \textbf{C}, observa que \textbf{C} proporciona siempre un pago mayor que \textbf{I} (pagos 2 frente a 1 si J1 juega \textbf{A}, y 5 frente a 4 si J1 juega \textbf{M}). Por tanto, \textbf{C} domina estrictamente a \textbf{I} y J2 elimina la estrategia \textbf{I}.

\end{tcolorbox}

\begin{tcolorbox}[colback=blue!10]
\begin{table}[H]
\centering
\begin{tabular}{c|cc}
 & \multicolumn{2}{c}{\textbf{Jugador 2}} \\ 
\textbf{Jugador 1} & C & D\\ \hline
A & (4,2) & (1,2)\\
M & (3,5) & (4,0)
\end{tabular}
\caption{Juego $G_1$ (EID)}
\label{tab:EID}
\end{table}

El jugador J1 sabe que J2 es racional y que además J2 sabe que J1 es racional, por lo que sabe que J2 ha eliminado \textbf{I}. Considerando el juego reducido, vemos que para J1 ninguna estrategia domina a otra, es decir, no hay dominancia débil, mientras que J2 compara ahora las estrategias \textbf{C} y \textbf{D}. Observa que \textbf{C} proporciona un pago al menos igual que \textbf{D} cuando J1 juega \textbf{A} (pagos 2 frente a 2) y un pago mayor cuando J1 juega \textbf{M} (pagos 5 frente a 0). Por tanto, \textbf{D} está débilmente dominada por \textbf{C}, y J2 elimina la estrategia \textbf{D}.

\begin{table}[H]
\centering
\begin{tabular}{c|c}
 & \multicolumn{1}{c}{\textbf{Jugador 2}} \\ 
\textbf{Jugador 1} & C\\ \hline
A & (4,2)\\
M & (3,5)
\end{tabular}
\caption{Juego $G_2$ (EID)}
\label{tab:EID}
\end{table}

Finalmente, el jugador J1 compara sus estrategias \textbf{A} y \textbf{M}. Observa que \textbf{A} proporciona un pago mayor que \textbf{M} (4 frente a 3), por lo que \textbf{M} está dominada por \textbf{A}. En consecuencia, J1 elimina la estrategia \textbf{M}.

\begin{table}[H]
\centering
\begin{tabular}{c|c}
 & \multicolumn{1}{c}{\textbf{Jugador 2}} \\ 
\textbf{Jugador 1} & C\\ \hline
A & (4,2)
\end{tabular}
\caption{Juego $G_3$ perfil superviviente único (EID)}
\label{tab:EID}
\end{table}

En conclusión, las únicas estrategias supervivientes al proceso de eliminación iterativa de estrategias débilmente dominadas son \textbf{A} para el jugador 1 y \textbf{C} para el jugador 2. Ambas constituyen el único perfil solución del juego, es decir, $\mathbf{S^{EID}}$ = \{(A,C)\}.
\end{tcolorbox}

Cabe mencionar que todos estos métodos son evidentemente aplicables a juegos expresados en su forma extensiva:

\begin{center}
\begin{tikzpicture}[
scale=0.8,
level distance=2cm,
level 1/.style={sibling distance=6cm},
level 2/.style={sibling distance=2.5cm}
]

\node[circle,draw]{J1}
child {node[circle,draw]{J2}
    child {node{\scriptsize (3,1)} edge from parent node[pos=0.5,left]{\scriptsize I}}
    child {node{\scriptsize (4,2)} edge from parent node[pos=0.5,above]{\scriptsize C}}
    child {node{\scriptsize (1,2)} edge from parent node[pos=0.5,right]{\scriptsize D}}
    edge from parent node[pos=0.5,above left]{\scriptsize A}
}
child {node[circle,draw]{J2}
    child {node{\scriptsize (2,4)} edge from parent node[pos=0.5,left]{\scriptsize I}}
    child {node{\scriptsize (3,5)} edge from parent node[pos=0.5,above]{\scriptsize C}}
    child {node{\scriptsize (4,0)} edge from parent node[pos=0.5,right]{\scriptsize D}}
    edge from parent node[pos=0.5,above]{\scriptsize M}
}
child {node[circle,draw]{J2}
    child {node{\scriptsize (1,0)} edge from parent node[pos=0.5,left]{\scriptsize I}}
    child {node{\scriptsize (2,1)} edge from parent node[pos=0.5,above]{\scriptsize C}}
    child {node{\scriptsize (0,3)} edge from parent node[pos=0.5,right]{\scriptsize D}}
    edge from parent node[pos=0.5,above right]{\scriptsize B}
};

\end{tikzpicture}
\end{center}

\begin{center}
\begin{tikzpicture}[
scale=0.8,
level distance=2cm,
level 1/.style={sibling distance=4cm},
level 2/.style={sibling distance=2.5cm},
every node/.style={font=\footnotesize}
]

\node[circle,draw]{J1}
child {node[circle,draw]{J2} 
    child {node{\scriptsize (3,1)} edge from parent node[pos=0.5,above]{\scriptsize C}}
    child {node{\scriptsize (1,2)} edge from parent node[pos=0.5,right]{\scriptsize D}}
    edge from parent node[pos=0.5,above left]{\scriptsize A}
}
child {node[circle,draw]{J2} 
    child {node{\scriptsize (3,5)} edge from parent node[pos=0.5,above]{\scriptsize C}}
    child {node{\scriptsize (4,0)} edge from parent node[pos=0.5,right]{\scriptsize D}}
    edge from parent node[pos=0.5,above]{\scriptsize M}
};

\end{tikzpicture}
\end{center}

\begin{center}
\begin{tikzpicture}[
scale=0.8,
level distance=2cm,
level 1/.style={sibling distance=3.5cm},
level 2/.style={sibling distance=2.5cm},
every node/.style={font=\footnotesize}
]

\node[circle,draw]{J1}
child {node[circle,draw]{J2} 
    child {node{\scriptsize (4,2)} edge from parent node[pos=0.5,above]{\scriptsize C}}
    edge from parent node[pos=0.5,above left]{\scriptsize A}
}
child {node[circle,draw]{J2} 
    child {node{\scriptsize (3,5)} edge from parent node[pos=0.5,above]{\scriptsize C}}
    edge from parent node[pos=0.5,above]{\scriptsize M}
};

\end{tikzpicture}
\end{center}

\begin{figure}[H]
\centering
\begin{tikzpicture}[
scale=0.8,
level distance=2cm,
level 1/.style={sibling distance=2.5cm},
level 2/.style={sibling distance=2.5cm},
every node/.style={font=\footnotesize}
]

\node[circle,draw]{J1}
child {node[circle,draw]{J2} 
    child {node{\scriptsize (4,2)} edge from parent node[pos=0.5,above]{\scriptsize C}}
    edge from parent node[pos=0.5,above]{\scriptsize A}
};

\end{tikzpicture}
\caption{Eliminación iterativa de estrategias: J1 elimina B porque A domina estrictamente a B, J2 elimina I porque C domina estrictamente a I, J2 elimina D porque C domina débilmente a D, y finalmente J1 elimina M. El perfil superviviente único es $(A,C)$.}
\label{fig:arbol}
\end{figure}

**Juegos resolubles por dominación**

**Definición 3.5.** En el juego finito o infinito $G = \{S_1,\ldots,S_n;u_1,\ldots,u_n\}$, decimos que G es **resoluble por dominación** si en el proceso de eliminación iterativa débil, usando el algoritmo estándar, quedan como supervivientes únicamente las estrategias $S^S_1 \subset S_1, \ldots,S^S_n \subset S_n$, de modo que se cumple lo siguiente para todo jugador i y para toda combinación $s_{-i}$ de estrategias supervivientes de los demás:

$$s_i,s'_i \in S^S_i \,\, \mbox{implica que} \,\, u_i(s_i,s_{-i}) = u_i(s'_i,s_{-i})$$

En el caso en que G es resoluble por dominación, a cada perfil de estrategias supervivientes $s^S \in S^S_1 \times \ldots \times S^S_s$ se le llama **equilibrio sofisticado**.

Cuando la solución que aportan UED o EIE sea única, también lo será la solución que aporte EID. Estaremos ante un juego resoluble por dominación.

\begin{tcolorbox}[colback=blue!10]
\textbf{Ejemplo 3.5} \\

Dado el juego

\begin{table}[H]
\centering
\begin{tabular}{c|ccc}
 & \multicolumn{3}{c}{\textbf{Jugador 2}} \\ 
\textbf{Jugador 1} & I & C & D\\ \hline
A & (5,y) & (5,4) & (9,0)\\
M & (1,7) & (2,5) & (8,6) \\
B & (2,3) & (1,4) & (8,3)
\end{tabular}
\caption{Juego resoluble por dominación}
\label{tab:ejemplo_dominacion}
\end{table}

\begin{itemize}
\item Si $y = 4$: se eliminan M y B de J1, D de J2. Soluciones: (A,I) y (A,C).  
\item Si $y = 5$: se eliminan M y B de J1, D de J2 en la primera etapa, luego C de J2. Solución única: (A,I).  
\end{itemize}

En los dos casos, podemos decir que el juego es resoluble por dominación, aunque en el primero de ellos hay múltiples perfiles solución (todos ellos equilibrios sofisticados).
\end{tcolorbox}



## Equilibrio de Nash
### Equilibrio de Nash en estrategias puras
### Equilibrio de Nash en estrategias mixtas

## Optimalidad de Pareto

## Equilibrio perfecto en subjuegos

